name: PR - Build and Test 

on:
  pull_request:
    branches: [ master ]

jobs:
  build-pack-push:
    env:
      project-path: ./src/EasyCqrs/EasyCqrs.csproj

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      
      - name: Restore dependencies
        run: dotnet restore ${{ env.project-path }}

      - name: Build with dotnet
        run: dotnet build ${{ env.project-path }} -c Release

      - name: Test
        run: dotnet test ${{ env.project-path }}      