name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./src/EasyCqrs

      - name: Build with dotnet
        run: dotnet build --configuration Release
        working-directory: ./src/EasyCqrs

      - name: Test
        run: dotnet test
        working-directory: ./src/EasyCqrs


      