name: Merge - Pack and Push

on:
  push:
    branches: [ deploy ]

jobs:
  build-pack-push:
    env:
      easycqrs-path: ./src/EasyCqrs/EasyCqrs.csproj

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      
      - name: Restore
        run: dotnet restore 

      - name: Build
        run: dotnet build  -c Release 
       
      - name: Test
        run: dotnet test    

      - name: Pack
        run: dotnet pack ${{ env.easycqrs-path }} -c Release -o output

      - name: Publish Nuget
        run: |
          cd output
          dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_SERVER }} --skip-duplicate