name: PR - Build and Test 

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  build-pack-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      
      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release 
       
      - name: Test
        run: dotnet test    