name: Pack and Push

on:
  release:
    types: [published]

jobs:
  build-pack-push:
    env:
      project-path: ./src/EasyCqrs/EasyCqrs.csproj

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Create NuGet Package
        run: dotnet pack ${{ env.project-path }} -c Release /p:Version=${{ github.event.release.tag_name }}"

      - name: Archive NuGet Package
        uses: actions/upload-artifact@v1
        with:
          name: TP.EasyCqrs
          path: ./src/EasyCqrs/bin/Release/EasyCqrs.${{ github.event.release.tag_name }}.nupkg

      - name: Publish Nuget Package
        run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_SERVER }} --skip-duplicate